### PR TITLE
Update dashboard

### PR DESCRIPTION
**Pull request by jwcastillo**
PR Dashboard closing 2022

It includes:
All available k6 metrics - prometheus
Apdex

Does not include:
Custom Metrics

### CODE REVIEW

**Review by codebien — CHANGES_REQUESTED** [review]
Hey @jwcastillo,
it seems the branch has some conflicts. Can you rebase, please?

**Comment by jwcastillo** [comment]
help me, I do not identify any conflict with main

**Comment by codebien** [comment]
Hey @jwcastillo,
the file with conflicts is `grafana/dashboards/dashboard-results.json`

You can pull the `main` branch's changes locally then move to your branch and try to rebase it, you should get the conflict and the specific lines.

**Review by codebien — COMMENTED** [review]
Hey @jwcastillo,
the file with conflicts is grafana/dashboards/dashboard-results.json

You can pull the main branch's changes locally then move to your branch and try to rebase it, you should get the conflict and the specific lines.

**Comment by jwcastillo** [comment]
ok

**Pull request closed without merging**
