### PR TITLE
Fix/strvals dependency

### PR DESCRIPTION
**Pull request by arukiidou**
github.com/kubernetes/helm v2.17.0+incompatible
to
helm.sh/helm/v3 v3.10.2

Signed-off-by: junya koyama <arukiidou@yahoo.co.jp>

### CODE REVIEW

**Comment by codebien** [comment]
Hey @arukiidou, thanks for your contribution :bow:

**Review by codebien — CHANGES_REQUESTED** [review]
@arukiidou can you rebase for resolving the conflicts, please?

**Review by codebien — APPROVED** [review]

**Comment by codebien** [comment]
@arukiidou apparently there are still conflicts

**Comment by arukiidou** [comment]
There appears to be no conflict🤔, so we'll start over tomorrow.

**Comment by arukiidou** [comment]
@codebien 
Sorry I did something wrong. I started over　#63,

**Pull request closed without merging**
