### PR TITLE
Remove labels with empty values

### PR DESCRIPTION
**Pull request by afajl**
Needed to remove empty labels to make this work with Thanos receive.

### CODE REVIEW

**Comment by codebien** [comment]
Hi @afajl,
thanks for your contribution. :bow: 

k6 doesn't add empty tags (so empty labels can't be generated). They are allowed as a custom tag defined by the user, are you scripting in the test this tag addition? Can you explain your use case and why you're doing it, please?

**Comment by codebien** [comment]
Hey @afajl, you're right, and in any case this is not allowed by definition from the spec. The Prometheus server does not enforce it and just removes it. We need to address this, thanks for reporting.

**Comment by codebien** [comment]
Hey @afajl, can you try the latest version and confirm that it works for you, please?

**Comment by afajl** [comment]
Yeah, that works fine. Thanks!

**Pull request closed without merging**
